<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <UserSecretsId>dotnet-FleetTelemetry.Simulator-0fdfb52f-d77f-40c9-8f4e-09d8b82c447c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\FleetTelemetry.Contracts\FleetTelemetry.Contracts.csproj" />
  </ItemGroup>
</Project>
